
# JDBC 接続情報（必須）
jdbcUrl: jdbc:postgresql://localhost:56432/todo
jdbcUser: todo
jdbcPass: todo
jdbcSchema: todo

# Entity のパッケージ名（必須）
entityPackage: jp.green_code.todo.entity

# Repository のパッケージ名（必須）
repositoryPackage: jp.green_code.todo.repository

# Java 最上位フォルダ（必須）
mainJavaDir: ../src/main/java

# Java Test 最上位フォルダ（テスト作成時必須）
testJavaDir: ../src/test/java

# 対象外テーブル（省略可）
#   記載のテーブルに対してはEntity, Repository, TestRepository のいずれも作成しない
excludedTableNames:
  - spring_session
  - spring_session_attributes

# Enum 型登録（省略可）
#   DBの型とJava (enum) の型を下の形式で指定します
#   status_enum: jp.green_code.demo.enum.StatusEnum
enumJavaTypeMappings:
  todo_status: jp.green_code.todo.enums.TodoStatusEnum

# UPDATE 対象外カラム（省略可）
#   テーブル名とカラム名を下の形式で指定します
#   table_name:
#     - column_name
#   テーブルに* を指定すると全テーブルのカラムが対象となります
excludeUpdateColumnsByTable:
  "*":
    - created_at
    - created_by

# INSERT 対象外カラム（省略可）
#   テーブル名とカラム名を下の形式で指定します
#   table_name:
#     - column_name
#   テーブルに* を指定すると全テーブルのカラムが対象となります
excludeInsertColumnsByTable:
  "*":
    - created_at

# 実体クラスの強制上書き（省略可）
#   初期値 false(しない)
#forceOverwriteImplementation: false

# テスト対象テーブル（省略可）
#   指定されたテーブルのcrud テストコードを作成します
#   テーブルにPK がない場合はテストは作成されません
testTargetTable:
  - account
  - todo
  - test_all
  - test_no_pk
  - test_one_pk
  - test_two_pk
  - test_all_with_default

# テスト対象外カラム（省略可）
#   テストコードから除外するカラムを指定します
#   先にテーブル名をtestTargetTable へ記載してください
#   テーブル名とカラム名を下の形式で指定します
#   table_name:
#     - column_name
#   テーブルに* を指定すると全テーブルのカラムが対象となります
testSkipColumnsByTable:
  "*":
    - modified_at
    - updated_at

#
# 以下、高度な設定
#

# 基底クラスのパッケージ名（省略可）
#   初期値 base
#basePackageName: base

# Entity クラスの接頭辞（省略可）
#   初期値 空文字列
#entityClassNamePrefix: ""

# Entity クラスの接尾辞（省略可）
#   初期値 空文字列
#entityClassNameSuffix: Entity

# Repository クラスの接頭辞（省略可）
#   初期値 空文字列
#repositoryClassNamePrefix: ""

# Repository クラスの接尾辞（省略可）
#   初期値 Repository
#repositoryClassNameSuffix: Repository

# TestRepository クラスの接頭辞（省略可）
#   初期値 Test
#testRepositoryClassNamePrefix: Test

# TestRepository クラスの接尾辞（省略可）
#   初期値 空文字列
#testRepositoryClassNameSuffix: Repository

# ヘルパークラス名（省略可）
#   初期値 RepositoryHelper
#repositoryHelperClassName: RepositoryHelper
