server:
  port: 52280
  servlet:
    session:
      cookie:
        # HTTPS 環境ではtrue
        secure: false
        # HTTPS 環境では__Host-SESSION
        name: SESSION
    encoding:
      charset: UTF-8
      force-response: true

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  multipart:
    enabled: true

  datasource:
    url: jdbc:postgresql://localhost:52232/todo?currentSchema=TODO
    username: todo
    password: todo
    driver-class-name: org.postgresql.Driver
    hikari:
      # サーバ上では100 程度が良い
      maximumPoolSize: 5

  # spring session
  session:
    store-type: jdbc

# アプリで使用するキーのトップレベルはappとする
# 外部ライブラリが使用するキーとの衝突を避ける
app:
  name: Todo
