# 本番環境用設定
# ローカル環境と異なる点のみ記載する
server:
  servlet:
    session:
      cookie:
        # HTTPS 環境限定のセキュリティ対策
        # cookie を堅牢にする
        secure: true
        name: __Host-SESSION

spring:
  # ローカル設定戻し　ここから
  thymeleaf:
    cache: true
    prefix: classpath:/templates/
  web:
    resources:
      static-locations: classpath:/static/
  # ローカル設定戻し　ここまで

app:
  name: やること
