services:
  postgres:
    image: postgres:16.3
    ports:
      - 56432:5432
    environment:
      - POSTGRES_USER=todo
      - POSTGRES_PASSWORD=todo
      - POSTGRES_DB=todo
      - TZ=Asia/Tokyo
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
