services:
  postgres:
    build:
      context: ./postgres
    ports:
      - 56432:5432
    environment:
      - POSTGRES_USER=todo
      - POSTGRES_PASSWORD=todo
      - POSTGRES_DB=todo
    healthcheck:
      test: psql -Utodo todo -c '\q'
